name: access to aws via access key

on:
  workflow_dispatch:

jobs:
  aws-s3:
    # runs-on: [self-hosted, awsactions]
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: zio file
        run: |
          zip my-function.zip my-function.js

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1          

      - name: AWS cli
        run: |
          aws s3 ls

      - name: AWS cli copy file to S3 bucket
        run: |
          aws lambda list-functions          
          # aws lambda create-function --function-name my-function --runtime nodejs18.x --zip-file fileb://my-function.zip --handler my-function.handler --role ${{ secrets.AWS_IAM_ROLE_LAMBDA }}
          # aws s3 cp glue.py s3://zytest1/ --recursive
          GLUE_JOB_NAME="glue-2"
          GLUE_SCRIPT_PATH="glue.py"
          S3_BUCKET="aws-glue-assets-339670971348-us-east-1"
          S3_KEY="glue.py"

          # Upload the script to S3
          aws s3 cp $GLUE_SCRIPT_PATH s3://$S3_BUCKET/$S3_KEY

          # Update the Glue job with the new script location
          aws glue update-job \
            --job-name $GLUE_JOB_NAME \
            --job-update Role=glue-actions,Command="{Name=glueetl,ScriptLocation=s3://$S3_BUCKET/$S3_KEY}"
