name: access to aws via access key

on:
  workflow_dispatch:

jobs:
  aws-s3:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1          

      - name: AWS cli
        run: |
          aws s3 ls

      - name: AWS cli copy file to S3 bucket
        run: |
          aws s3 cp README.md s3://zytest1/
          
