name: access to aws via access key

on:
  workflow_dispatch:

jobs:
  aws-s3:
    runs-on: [self-hosted, awsactions]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1          

      - name: AWS cli
        run: |
          aws s3 ls

      - name: AWS cli copy file to S3 bucket
        run: |
          aws s3 cp . s3://zytest1/ --recursive
          aws lambda create-function --function-name my-function --runtime nodejs18.x --zip-file fileb://my-function.zip --handler my-function.handler 
