name: auto merge 2 branches

on:
  pull_request:  
    types:
      - closed      
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}

      - name: print name of branch
        run: |
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Pull request event type: ${{ github.event.action }}"
          echo "Default branch: ${{ github.event.repository.default_branch }}"
      - name: Merge PR branch into default branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@github.com"
          git fetch --all          
          git checkout ${{ github.event.pull_request.base.ref }}
          git branch
          git pull           
          git checkout ${{ github.event.repository.default_branch }}
          git branch
          git pull origin ${{ github.event.repository.default_branch }}
          git merge ${{ github.event.pull_request.base.ref }} -X theirs --allow-unrelated-histories --no-ff -m "Merging PR branch into default branch"
          git push origin ${{ github.event.repository.default_branch }}    
