name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get semver based on pull request label
        id: semver
        uses: snsinahub-org/semver@v4.0.1
        with:
          type: 'MAJOR'
          prefix: 'v'
          body: 'Release body text...'
          create-release: 'yes'
          files: |
            Dockerfile
            action.yml
            code-coverage-report.zip

      - name: Print version
        run: |
          echo ${{ steps.semver.outputs.version }}
